// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// political_views.js
export const FETCH_POLITICAL_VIEWS_SUCCESS = 'FETCH_POLITICAL_VIEWS_SUCCESS'
export const FETCH_POLITICAL_VIEWS_FAILURE = 'FETCH_POLITICAL_VIEWS_FAILURE'